<?php
/*
  Author: B0zz
  Date: 2003/03/16

 * userfooter.inc -- This file can be used to add Custom html
 * 		     at the top of each page execept the login
 *		     and logout page
 *
 * Copyright (c) 1999-2003 The Owl Project Team
 * Licensed under the GNU GPL. For full terms see the file COPYING.
 *


 EXAMPLE move the 3 lines below after the ?>:
<p align="center"><b><font size="2">You may place extra stuff & navigation here</font></b></p>
<center>
<br>
*/
?>
